version: "3.9"

services:
  db_auth:
    container_name: db_spring_boot
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_spring_boot
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=root
    image: mysql:8-debian
